### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xichenyun** [KeJunMao/wan-xiao-ykt#1]
P:\wan-xiao-ykt-master>npm run web

> 17wanxiao@1.0.0 web
> cd web && npm i && npm run build

up to date, audited 178 packages in 1s

6 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (3 moderate, 3 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> svelte-app@1.0.0 build
> rollup -c

src/main.js → public/build/bundle.js...
created public/build/bundle.js in 795ms

P:\wan-xiao-ykt-master>npm run cli

> 17wanxiao@1.0.0 cli
> node index.mjs

file:///P:/wan-xiao-ykt-master/utils/analysis.mjs:57
  data.forEach((cell) => {
       ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at analysis (file:///P:/wan-xiao-ykt-master/utils/analysis.mjs:57:8)
    at file:///P:/wan-xiao-ykt-master/index.mjs:20:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0

**Comment by KeJunMao** [comment]
这个应该不能用了，你可以看看源码然后尝试修复下
